<!--
*Author：jxx
 *Contact：283591387@qq.com
 *代码由框架生成,任何更改都可能导致被代码生成器覆盖
 *业务请在@/extension/system/cust/View_import_customer_maintain.js此处编写
 -->
<template>
    <view-grid ref="grid"
               :columns="columns"
               :detail="detail"
               :editFormFields="editFormFields"
               :editFormOptions="editFormOptions"
               :searchFormFields="searchFormFields"
               :searchFormOptions="searchFormOptions"
               :table="table"
               :extend="extend">
    </view-grid>
</template>
<script>
    import extend from "@/extension/basic/cust/View_import_customer_maintain.js";
    import { ref, defineComponent } from "vue";
    export default defineComponent({
        setup() {
            const table = ref({
                key: 'custtransfer_dbid',
                footer: "Foots",
                cnName: 'Import Customer Maintain',
                name: 'cust/View_import_customer_maintain',
                url: "/View_import_customer_maintain/",
                sortName: "created_date"
            });
            const editFormFields = ref({"division":"","cust_id":"","cust_name":"","invoice_name":"","cust_zip_id_city_name":"","invoice_zip_id_city_name":"","cust_zip_id":"","invoice_zip_id":"","cust_address":"","invoice_address":"","owner":"","tax_id":"","contact":"","tel_no":"","fax_no":"","email":"","territory_id":"","doh_institute_no":"","ctrl_drug_no":"","ctrl_drug_contact":"","doh_type":"","margin_type":"","is_controll":"","is_private":"","status":"","own_by_hospital":"","med_group_cust_id":"","delv_group_cust_id":"","own_hospital_cust_id":"","own_hospital_name":"","created_date":"","created_username":"","modified_username":"","modified_date":"","remarks":"","med_group":"","delv_group":"","own_hospital":""});
            const editFormOptions = ref([[{"dataKey":"division","data":[],"title":"Division","field":"division","type":"select"}],
                              [{"title":"Customer Code","field":"cust_id","type":"text"}],
                              [{"title":"Customer","required":true,"field":"cust_name","type":"text"},
                               {"title":"Invoice Name","required":true,"field":"invoice_name","type":"text"}],
                              [{"dataKey":"viat_city","data":[],"title":"Customer City Name","required":true,"field":"cust_zip_id_city_name","type":"select"},
                               {"dataKey":"viat_city","data":[],"title":"Invoice City Name","required":true,"field":"invoice_zip_id_city_name","type":"select"}],
                              [{"dataKey":"viat_city_zone","data":[],"title":"Customer Zip Code","required":true,"field":"cust_zip_id","type":"select"},
                               {"dataKey":"viat_city_zone","data":[],"title":"Invoice Zip Id","required":true,"field":"invoice_zip_id","type":"select"}],
                              [{"title":"Customer address","required":true,"field":"cust_address","type":"text"},
                               {"title":"Invoice address","required":true,"field":"invoice_address","type":"text"}],
                              [{"title":"Owner","required":true,"field":"owner","type":"text"},
                               {"title":"Tax ID","field":"tax_id","type":"text"}],
                              [{"title":"Contact","field":"contact","type":"text"},
                               {"title":"Telephone","required":true,"field":"tel_no","type":"text"}],
                              [{"title":"Fax","field":"fax_no","type":"text"},
                               {"title":"Email","field":"email","type":"text"}],
                              [{"title":"Territory ID","required":true,"field":"territory_id","type":"text"}],
                              [{"title":"NHI Institute NO","field":"doh_institute_no","type":"text"},
                               {"title":"Controlled Medicine Certificate No","field":"ctrl_drug_no","type":"text"}],
                              [{"dataKey":"doh_type","data":[],"title":"DOH Type ","required":true,"field":"doh_type","type":"select"},
                               {"title":"Controlled Medicine Contact","field":"ctrl_drug_contact","type":"text"}],
                              [{"dataKey":"doh_type","data":[],"title":"Margin Type","required":true,"field":"margin_type","type":"select"},
                               {"dataKey":"Status3","data":[],"title":"Is Controlled","field":"is_controll","type":"select"}],
                              [{"dataKey":"PublicPrivate","data":[],"title":"Public/Private","field":"is_private","type":"select"},
                               {"dataKey":"Status_YN","data":[],"title":"Status","field":"status","type":"select"}],
                              [{"dataKey":"Status3","data":[],"title":"Is Hospital Owned Drug Store","required":true,"field":"own_by_hospital","type":"select"},
                               {"title":"Medical Group","field":"med_group_cust_id","type":"text"}],
                              [{"title":"Own Hospital","field":"own_hospital_cust_id","type":"text"},
                               {"title":"Price Group","field":"delv_group_cust_id","type":"text"}],
                              [{"title":"Own Hospital Name","field":"own_hospital_name","type":"text"}],
                              [{"title":"Created User","field":"created_username"},
                               {"title":"Transfer Date","field":"created_date","type":"datetime"}],
                              [{"title":"Update User","field":"modified_username","type":"text"},
                               {"title":"Update Date","field":"modified_date","type":"datetime"}],
                              [{"title":"Note","field":"remarks","type":"textarea"}]]);
            const searchFormFields = ref({"cust_name":"","state":"","source":""});
            const searchFormOptions = ref([[{"dataKey":"import_source","data":[],"title":"Import Source","field":"source","type":"select"},{"title":"Customer","field":"cust_name","type":"like"},{"dataKey":"Process_Stats","data":[],"title":"Process Status","field":"state","type":"select"}]]);
            const columns = ref([{field:'territory_id',title:'Territory ID',type:'string',width:110,require:true,align:'left',sort:true},
                       {field:'emp_cname',title:'Name',type:'string',width:110,align:'left'},
                       {field:'cust_name',title:'Customer',type:'string',width:120,require:true,align:'left'},
                       {field:'created_date',title:'Transfer Date',type:'datetime',width:110,align:'left',sort:true},
                       {field:'state',title:'Process Status',type:'string',bind:{ key:'Process_Stats',data:[]},width:110,align:'left'},
                       {field:'custtransfer_dbid',title:'custtransfer_dbid',type:'guid',width:110,hidden:true,require:true,align:'left'},
                       {field:'bid_no',title:'bid_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'emp_id',title:'emp_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'entity',title:'entity',type:'string',width:110,hidden:true,align:'left'},
                       {field:'division',title:'Division',type:'string',bind:{ key:'division',data:[]},width:110,hidden:true,align:'left'},
                       {field:'cust_id',title:'Customer Code',type:'string',width:110,hidden:true,align:'left'},
                       {field:'cust_zip_id',title:'Customer Zip Code',type:'string',bind:{ key:'viat_city_zone',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'cust_address',title:'Customer address',type:'string',width:180,hidden:true,require:true,align:'left'},
                       {field:'invoice_zip_id',title:'Invoice Zip Id',type:'string',bind:{ key:'viat_city_zone',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'invoice_name',title:'Invoice Name',type:'string',width:120,hidden:true,require:true,align:'left'},
                       {field:'invoice_address',title:'Invoice address',type:'string',width:180,hidden:true,require:true,align:'left'},
                       {field:'owner',title:'Owner',type:'string',width:120,hidden:true,require:true,align:'left'},
                       {field:'tax_id',title:'Tax ID',type:'string',width:110,hidden:true,align:'left'},
                       {field:'contact',title:'Contact',type:'string',width:120,hidden:true,align:'left'},
                       {field:'tel_no',title:'Telephone',type:'string',width:110,hidden:true,require:true,align:'left'},
                       {field:'fax_no',title:'Fax',type:'string',width:110,hidden:true,align:'left'},
                       {field:'email',title:'Email',type:'string',width:110,hidden:true,align:'left'},
                       {field:'doh_institute_no',title:'NHI Institute NO',type:'string',width:110,hidden:true,align:'left'},
                       {field:'ctrl_drug_no',title:'Controlled Medicine Certificate No',type:'string',width:110,hidden:true,align:'left'},
                       {field:'ctrl_drug_contact',title:'Controlled Medicine Contact',type:'string',width:120,hidden:true,align:'left'},
                       {field:'doh_type',title:'DOH Type ',type:'string',bind:{ key:'doh_type',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'margin_type',title:'Margin Type',type:'string',bind:{ key:'doh_type',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'is_controll',title:'Is Controlled',type:'string',bind:{ key:'Status3',data:[]},width:110,hidden:true,align:'left'},
                       {field:'is_private',title:'Public/Private',type:'string',bind:{ key:'PublicPrivate',data:[]},width:110,hidden:true,align:'left'},
                       {field:'own_by_hospital',title:'Is Hospital Owned Drug Store',type:'string',bind:{ key:'Status3',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'med_group_cust_id',title:'Medical Group',type:'string',width:110,hidden:true,align:'left'},
                       {field:'delv_group_cust_id',title:'Price Group',type:'string',width:110,hidden:true,align:'left'},
                       {field:'own_hospital_cust_id',title:'Own Hospital',type:'string',width:110,hidden:true,align:'left'},
                       {field:'status',title:'Status',type:'string',bind:{ key:'Status_YN',data:[]},width:110,hidden:true,align:'left'},
                       {field:'remarks',title:'Note',type:'string',width:220,hidden:true,align:'left'},
                       {field:'source',title:'Import Source',type:'string',bind:{ key:'import_source',data:[]},width:110,hidden:true,align:'left'},
                       {field:'note',title:'note',type:'string',width:220,hidden:true,align:'left'},
                       {field:'created_user',title:'created_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'created_username',title:'Created User',type:'string',width:110,hidden:true,align:'left'},
                       {field:'created_client',title:'created_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'created_clientusername',title:'created_clientusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modified_user',title:'modified_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'modified_username',title:'Update User',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modified_client',title:'modified_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'modified_clientusername',title:'modified_clientusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modified_date',title:'Update Date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'cust_zip_id_dbid',title:'cust_zip_id_dbid',type:'int',width:110,hidden:true,require:true,align:'left'},
                       {field:'cust_zip_id_zip_name',title:'cust_zip_id_zip_name',type:'string',width:110,hidden:true,require:true,align:'left'},
                       {field:'cust_zip_id_city_name',title:'Customer City Name',type:'string',bind:{ key:'viat_city',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'invoice_zip_id_dbid',title:'invoice_zip_id_dbid',type:'int',width:110,hidden:true,require:true,align:'left'},
                       {field:'invoice_zip_id_zip_name',title:'invoice_zip_id_zip_name',type:'string',width:110,hidden:true,require:true,align:'left'},
                       {field:'invoice_zip_id_city_name',title:'Invoice City Name',type:'string',bind:{ key:'viat_city',data:[]},width:110,hidden:true,require:true,align:'left'},
                       {field:'own_hospital_name',title:'Own Hospital Name',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_cust_zip_name',title:'com_cust_zip_name',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_cust_city_name',title:'com_cust_city_name',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_invoice_zip_name',title:'com_invoice_zip_name',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_invoice_city_name',title:'com_invoice_city_name',type:'string',width:110,hidden:true,align:'left'},
                       {field:'cust_dbid',title:'cust_dbid',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'com_dbid',title:'com_dbid',type:'int',width:110,hidden:true,align:'left'},
                       {field:'com_created_user',title:'com_created_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'com_created_client',title:'com_created_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'com_created_date',title:'com_created_date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'com_modified_user',title:'com_modified_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'com_modified_client',title:'com_modified_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'com_modified_date',title:'com_modified_date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'com_entity',title:'com_entity',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_division',title:'com_division',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_cust_id',title:'com_cust_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_cust_name',title:'com_cust_name',type:'string',width:120,hidden:true,align:'left'},
                       {field:'com_cust_zip_id',title:'com_cust_zip_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_cust_address',title:'com_cust_address',type:'string',width:180,hidden:true,align:'left'},
                       {field:'com_invoice_zip_id',title:'com_invoice_zip_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_invoice_name',title:'com_invoice_name',type:'string',width:120,hidden:true,align:'left'},
                       {field:'com_invoice_address',title:'com_invoice_address',type:'string',width:180,hidden:true,align:'left'},
                       {field:'com_owner',title:'com_owner',type:'string',width:120,hidden:true,align:'left'},
                       {field:'com_tax_id',title:'com_tax_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_contact',title:'com_contact',type:'string',width:120,hidden:true,align:'left'},
                       {field:'com_tel_no',title:'com_tel_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_fax_no',title:'com_fax_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_email',title:'com_email',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_territory_id',title:'com_territory_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_doh_institute_no',title:'com_doh_institute_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_ctrl_drug_no',title:'com_ctrl_drug_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_ctrl_drug_contact',title:'com_ctrl_drug_contact',type:'string',width:120,hidden:true,align:'left'},
                       {field:'com_doh_type',title:'com_doh_type',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_margin_type',title:'com_margin_type',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_is_contract',title:'com_is_contract',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_is_private',title:'com_is_private',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_own_by_hospital',title:'com_own_by_hospital',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_own_hospital',title:'com_own_hospital',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'com_med_group',title:'com_med_group',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'com_delv_group',title:'com_delv_group',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'com_new_cust_id',title:'com_new_cust_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_inactive_date',title:'com_inactive_date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'com_status',title:'com_status',type:'string',width:110,hidden:true,align:'left'},
                       {field:'com_remarks',title:'com_remarks',type:'string',width:220,hidden:true,align:'left'},
                       {field:'com_source',title:'com_source',type:'string',width:110,hidden:true,align:'left'},
                       {field:'createdusername',title:'createdusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modifiedusername',title:'modifiedusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'own_hospital_custname',title:'Own Hospital Custname',type:'string',width:120,hidden:true,align:'left'},
                       {field:'med_group_custname',title:'med_group_custname',type:'string',width:120,hidden:true,align:'left'},
                       {field:'delv_group_custname',title:'delv_group_custname',type:'string',width:120,hidden:true,align:'left'},
                       {field:'C1',title:'C1',type:'string',width:110,hidden:true,align:'left'},
                       {field:'is_contract',title:'Is Contracted',type:'string',width:110,hidden:true,align:'left'},
                       {field:'inactive_date',title:'Inactivated Date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'new_cust_id',title:'New Customer',type:'string',width:110,hidden:true,align:'left'},
                       {field:'delv_group',title:'Price Group',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'med_group',title:'Medical Group',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'own_hospital',title:'Own Hospital Cust ID',type:'guid',width:110,hidden:true,align:'left'},
                       {field:'dbid',title:'dbid',type:'int',width:80,hidden:true,require:true,align:'left'}]);
            const detail = ref({
                cnName: "Import Customer Maintain Detail",
                table: "View_app_cust_delivery_transfer",
                columns: [{field:'seq_no',title:'SeqNo',type:'decimal',width:110,edit:{type:''},align:'left',sort:true},
                       {field:'delivery_name',title:'Delivery Name',type:'string',width:120,edit:{type:''},align:'left'},
                       {field:'delivery_zip_id',title:'Zip',type:'string',width:110,edit:{type:''},align:'left'},
                       {field:'delivery_addr',title:'Delivery Address',type:'string',width:180,edit:{type:''},align:'left'},
                       {field:'delivery_contact',title:'Delivery Contact',type:'string',width:120,edit:{type:''},align:'left'},
                       {field:'delivery_tel_no',title:'Telephone',type:'string',width:110,edit:{type:''},align:'left'},
                       {field:'custdeltransfer_dbid',title:'custdeltransfer_dbid',type:'guid',width:110,hidden:true,require:true,align:'left'},
                       {field:'dbid',title:'dbid',type:'int',width:110,hidden:true,require:true,align:'left'},
                       {field:'entity',title:'entity',type:'string',width:110,hidden:true,align:'left'},
                       {field:'emp_id',title:'emp_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'bid_no',title:'bid_no',type:'string',width:110,hidden:true,align:'left'},
                       {field:'division',title:'division',type:'string',width:110,hidden:true,align:'left'},
                       {field:'cust_id',title:'cust_id',type:'string',width:110,hidden:true,align:'left'},
                       {field:'created_user',title:'created_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'created_username',title:'created_username',type:'string',width:110,hidden:true,align:'left'},
                       {field:'created_client',title:'created_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'created_clientusername',title:'created_clientusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'created_date',title:'created_date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'modified_user',title:'modified_user',type:'int',width:110,hidden:true,align:'left'},
                       {field:'modified_username',title:'modified_username',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modified_client',title:'modified_client',type:'int',width:110,hidden:true,align:'left'},
                       {field:'modified_clientusername',title:'modified_clientusername',type:'string',width:110,hidden:true,align:'left'},
                       {field:'modified_date',title:'modified_date',type:'datetime',width:110,hidden:true,align:'left',sort:true},
                       {field:'custtransfer_dbid',title:'custtransfer_dbid',type:'guid',width:110,hidden:true,require:true,align:'left'}],
                sortName: "seq_no",
                key: "custdeltransfer_dbid"
            });
            return {
                table,
                extend,
                editFormFields,
                editFormOptions,
                searchFormFields,
                searchFormOptions,
                columns,
                detail,
            };
        },
    });
</script>
